### ISSUE TITLE
是否可以丰富下 使用文档 ?

### ISSUE THREAD

**Issue by rfyiamcool** [ctripcorp/nephele#57]
我个人对图片服务很感兴趣，奈何nephele的文档有些简略了.  开源要文档先行的，请携程团队抽时间补充下基本的文档，比如 api文档、使用及部署文档 等

谢谢

**Comment by wuchengcheng2016** [comment]
谢谢你的关注与建议，最近团队有紧急任务暂时抽身于nephele的开源工作，近期就会回来，回来之后肯定会尽快完善文档。
再次感谢。
